@extends('admin.layouts.admin')

@section('title', 'Dashboard')

@php
    $categoryCounts = $stats['category_breakdown'] ?? [];
    $maxCategory = max(1, ...array_values($categoryCounts));
@endphp

@section('content')
<div class="space-y-8">
    <section class="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-5">
        <div><p class="text-[11px] uppercase tracking-[.18em] text-gold-600 font-bold">Today at a glance</p><h2 class="admin-display text-5xl leading-none text-ink mt-3">Keep the community<br><em class="text-plum-700">moving with care.</em></h2><p class="text-sm text-ivory-600 mt-4 max-w-xl">Review the moments that need human attention first: new profiles, protected photos, verification, and member safety.</p></div>
        <a href="{{ route('admin.profiles.pending') }}" class="btn btn-primary self-start lg:self-auto"><i class="fa-solid fa-user-check"></i> Review approvals @if(($stats['pending_approval'] ?? 0) > 0)<span class="bg-gold-300 text-plum-900 rounded-full px-2 py-1 text-xs">{{ $stats['pending_approval'] }}</span>@endif</a>
    </section>

    <section class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-5 gap-4" aria-label="Key metrics">
        <div class="admin-card admin-kpi p-5"><p class="text-xs text-ivory-600">Members</p><p class="admin-display text-4xl text-ink mt-2">{{ number_format($stats['total_users'] ?? 0) }}</p><p class="text-xs text-trust mt-2">{{ $stats['today_registrations'] ?? 0 }} joined today</p></div>
        <div class="admin-card admin-kpi p-5"><p class="text-xs text-ivory-600">Awaiting review</p><p class="admin-display text-4xl text-ink mt-2">{{ number_format($stats['pending_approval'] ?? 0) }}</p><a href="{{ route('admin.profiles.pending') }}" class="text-xs text-plum-700 font-semibold mt-2 inline-block">Open queue →</a></div>
        <div class="admin-card admin-kpi p-5"><p class="text-xs text-ivory-600">Premium members</p><p class="admin-display text-4xl text-ink mt-2">{{ number_format($stats['premium_users'] ?? 0) }}</p><p class="text-xs text-ivory-600 mt-2">Current active plans</p></div>
        <div class="admin-card admin-kpi p-5"><p class="text-xs text-ivory-600">This month's revenue</p><p class="admin-display text-4xl text-ink mt-2">₹{{ number_format($stats['monthly_revenue'] ?? 0) }}</p><p class="text-xs text-ivory-600 mt-2">All time ₹{{ number_format($stats['total_revenue'] ?? 0) }}</p></div>
        <div class="admin-card admin-kpi p-5"><p class="text-xs text-ivory-600">Accepted interests</p><p class="admin-display text-4xl text-ink mt-2">{{ number_format($stats['total_matches'] ?? 0) }}</p><p class="text-xs text-trust mt-2">{{ number_format($stats['active_today'] ?? 0) }} active today</p></div>
    </section>

    <section class="grid xl:grid-cols-[1.1fr_.9fr] gap-6">
        <div class="admin-card p-6 sm:p-8">
            <div class="flex items-start justify-between gap-4"><div><p class="text-[10px] uppercase tracking-[.16em] text-gold-600 font-bold">Community shape</p><h3 class="admin-display text-3xl text-ink mt-2">Who is finding Advaita?</h3></div><a href="{{ route('admin.members') }}" class="text-xs font-semibold text-plum-700">View members →</a></div>
            <div class="mt-8 space-y-5">
                @foreach([['label' => 'General', 'key' => 'general', 'color' => 'bg-rose-500'], ['label' => 'Divyangjan', 'key' => 'physically_challenged', 'color' => 'bg-plum-700'], ['label' => 'Hearing & speech', 'key' => 'hearing_speech', 'color' => 'bg-trust'], ['label' => 'Vitiligo', 'key' => 'vitiligo', 'color' => 'bg-gold-500']] as $category)
                    @php $count = $categoryCounts[$category['key']] ?? 0; @endphp
                    <div><div class="flex items-center justify-between mb-2"><span class="text-sm font-semibold text-ink">{{ $category['label'] }}</span><span class="text-sm text-ivory-600">{{ number_format($count) }}</span></div><div class="h-2 bg-ivory-200 overflow-hidden"><div class="h-full {{ $category['color'] }}" style="width: {{ min(100, ($count / $maxCategory) * 100) }}%"></div></div></div>
                @endforeach
            </div>
            <p class="text-xs text-ivory-600 mt-7 pt-5 border-t border-ivory-300">These counts come from the existing profile category data. No presentation-layer estimates are added.</p>
        </div>
        <div class="admin-card p-6 sm:p-8 bg-plum-900 text-white"><p class="text-[10px] uppercase tracking-[.16em] text-gold-300 font-bold">Trust queue</p><h3 class="admin-display text-4xl text-white mt-3">Small actions<br><em class="text-gold-300">build confidence.</em></h3><div class="mt-8 space-y-3"><a href="{{ route('admin.profiles.pending') }}" class="flex items-center justify-between gap-4 border-t border-white/15 py-4 text-sm hover:text-gold-300"><span><i class="fa-solid fa-user-check w-6 text-gold-300"></i>Profiles awaiting approval</span><strong>{{ $stats['pending_approval'] ?? 0 }} →</strong></a><a href="{{ route('admin.photos.pending') }}" class="flex items-center justify-between gap-4 border-t border-white/15 py-4 text-sm hover:text-gold-300"><span><i class="fa-solid fa-image w-6 text-gold-300"></i>Photos awaiting review</span><strong>{{ $stats['pending_photos'] ?? 0 }} →</strong></a><a href="{{ route('admin.udid') }}" class="flex items-center justify-between gap-4 border-y border-white/15 py-4 text-sm hover:text-gold-300"><span><i class="fa-solid fa-id-card w-6 text-gold-300"></i>UDID verification</span><strong>Open →</strong></a></div></div>
    </section>

    <section class="grid xl:grid-cols-2 gap-6">
        <div class="admin-card overflow-hidden"><div class="p-6 flex items-end justify-between"><div><p class="text-[10px] uppercase tracking-[.16em] text-gold-600 font-bold">Latest movement</p><h3 class="admin-display text-3xl text-ink mt-2">New members</h3></div><a href="{{ route('admin.members') }}" class="text-xs text-plum-700 font-semibold">All members →</a></div><div class="overflow-x-auto"><table class="admin-table min-w-full text-left"><thead><tr><th class="px-6 pb-3">Member</th><th class="px-6 pb-3">Category</th><th class="px-6 pb-3">Status</th><th class="px-6 pb-3">Joined</th></tr></thead><tbody>@forelse($recentRegistrations as $user)<tr><td class="px-6 py-4"><p class="font-semibold text-sm text-ink">{{ $user->name }}</p><p class="text-xs text-ivory-600">{{ $user->unique_id }}</p></td><td class="px-6 py-4 text-xs text-ivory-600">{{ $user->profile?->category_display_name ?? ucfirst(str_replace('_', ' ', $user->profile?->profile_category ?? 'General')) }}</td><td class="px-6 py-4"><span class="text-xs font-semibold {{ $user->profile_status === 'pending' ? 'text-amber-700' : 'text-trust' }}">{{ ucfirst($user->profile_status) }}</span></td><td class="px-6 py-4 text-xs text-ivory-600">{{ $user->created_at->diffForHumans() }}</td></tr>@empty<tr><td colspan="4" class="px-6 py-10 text-center text-sm text-ivory-600">No registrations to review yet.</td></tr>@endforelse</tbody></table></div></div>
        <div class="admin-card overflow-hidden"><div class="p-6 flex items-end justify-between"><div><p class="text-[10px] uppercase tracking-[.16em] text-gold-600 font-bold">Revenue movement</p><h3 class="admin-display text-3xl text-ink mt-2">Recent payments</h3></div><a href="{{ route('admin.analytics') }}" class="text-xs text-plum-700 font-semibold">Open analytics →</a></div><div class="overflow-x-auto"><table class="admin-table min-w-full text-left"><thead><tr><th class="px-6 pb-3">Member</th><th class="px-6 pb-3">Plan</th><th class="px-6 pb-3">Amount</th></tr></thead><tbody>@forelse($recentPayments as $payment)<tr><td class="px-6 py-4"><p class="font-semibold text-sm text-ink">{{ $payment->user->name }}</p><p class="text-xs text-ivory-600">{{ $payment->created_at->diffForHumans() }}</p></td><td class="px-6 py-4 text-xs text-ivory-600">{{ $payment->package?->name ?? 'N/A' }}</td><td class="px-6 py-4 text-sm font-semibold text-trust">₹{{ number_format($payment->amount) }}</td></tr>@empty<tr><td colspan="3" class="px-6 py-10 text-center text-sm text-ivory-600">No completed payments yet.</td></tr>@endforelse</tbody></table></div></div>
    </section>

    <section class="admin-card p-6"><div class="flex items-center justify-between mb-5"><div><p class="text-[10px] uppercase tracking-[.16em] text-gold-600 font-bold">Shortcuts</p><h3 class="admin-display text-3xl text-ink mt-2">What needs your attention?</h3></div></div><div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3"><a href="{{ route('admin.profiles.pending') }}" class="p-4 border border-ivory-300 hover:border-plum-300 transition-colors"><i class="fa-solid fa-user-check text-plum-700"></i><span class="block text-xs font-semibold mt-3">Profiles</span></a><a href="{{ route('admin.photos.pending') }}" class="p-4 border border-ivory-300 hover:border-plum-300 transition-colors"><i class="fa-solid fa-images text-plum-700"></i><span class="block text-xs font-semibold mt-3">Photos</span></a><a href="{{ route('admin.members') }}" class="p-4 border border-ivory-300 hover:border-plum-300 transition-colors"><i class="fa-solid fa-users text-plum-700"></i><span class="block text-xs font-semibold mt-3">Members</span></a><a href="{{ route('admin.udid') }}" class="p-4 border border-ivory-300 hover:border-plum-300 transition-colors"><i class="fa-solid fa-id-card text-plum-700"></i><span class="block text-xs font-semibold mt-3">UDID</span></a><a href="{{ route('admin.reports') }}" class="p-4 border border-ivory-300 hover:border-plum-300 transition-colors"><i class="fa-solid fa-flag text-plum-700"></i><span class="block text-xs font-semibold mt-3">Reports</span></a><a href="{{ route('admin.settings') }}" class="p-4 border border-ivory-300 hover:border-plum-300 transition-colors"><i class="fa-solid fa-sliders text-plum-700"></i><span class="block text-xs font-semibold mt-3">Settings</span></a></div></section>
</div>
@endsection
